"""Add game_user Association Table

Revision ID: 9255a97248d8
Revises: 1527dceec427
Create Date: 2023-05-07 20:37:40.467471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9255a97248d8'
down_revision = '1527dceec427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
