"""Add game_user Association Table

Revision ID: 99be5e4587b5
Revises: 9255a97248d8
Create Date: 2023-05-07 20:38:00.849364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99be5e4587b5'
down_revision = '9255a97248d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
